### ISSUE TITLE
Setting state in SignInForm component

### ISSUE THREAD

**Issue by Sangsom** [rwieruch/learn-react-firebase-book#3]
Hey first, of all thanks for a great tutorial I'm now reading the book and trying to understand magic of Firebase..

I was wondering about the `onSubmit` method in `SignInForm` component, you are updating component state by using fat arrow function `this.setState(() => ({ ...INITIAL_STATE }))` after the user authentification has been done successfully, is there any reason why you do so instead of `this.setState({...INITIAL_STATE})`.

P.s. it's in chapter 3

**Comment by rwieruch** [comment]
No. Since the previous state and previous props aren't used, using the object over the function is totally valid. Thanks for pointing this out :) Are you able to open a PR for all these cases? Otherwise, I will do it in the future :)

**Comment by Sangsom** [comment]
Sure, I'll do this.
