### ISSUE TITLE
src/components/SignUp.js - fields need to reference `this.state`

### ISSUE THREAD

**Issue by johnnydecimal** [rwieruch/learn-react-firebase-book#6]
Hi Robin! Thanks for the book, enjoying it so far.

On p20/21 of the PDF, I have the following code:
```javascript
<input
  value={username}
  onChange={event => this.setState(byPropKey('username', event.target.value)\
type="text"
  placeholder="Full Name"
/>
```

This caused an error for me, corrected by updating `value={username}` to `value={this.state.username}`.

I hope that's right, as I'm just learning React. :-)

Thanks,
j.

**Comment by johnnydecimal** [comment]
Ah, I've just seen the block above which uses deconstruction to pull out those variables.

That block just needs to be made bold to indicate that it's the first time it's appeared.

**Comment by rwieruch** [comment]
Thanks for pointing it out @jen729w Can you find the position in the manuscript as well? Maybe you are able to open a Pull Request for it. I have a hard time finding it :)

**Comment by johnnydecimal** [comment]
Done, I think. In the process I learned how to create a pull request! :-)

**Comment by rwieruch** [comment]
That's perfect! Welcome to open source @jen729w 🎉
